### ISSUE TITLE
Compatibility fix (Cursed Items Revision)

### ISSUE THREAD

**Issue by Salk73** [Gibberlings3/SpellRevisions#122]
Hello!

Could you please change this piece of code:

```
COPY ~spell_rev\spwi1##\spwi110.spl~     ~override~  // Identify
  SAY NAME1 @417    SAY UNIDENTIFIED_DESC @418
COPY ~spell_rev\spwi1##\scrl75.itm~      ~override~
  SAY NAME2 @417    SAY IDENTIFIED_DESC   @418
```

to this?

```
ACTION_IF NOT MOD_IS_INSTALLED ~cursed_items.tp2~ 0 BEGIN
COPY ~spell_rev\spwi1##\spwi110.spl~     ~override~  // Identify
  SAY NAME1 @417    SAY UNIDENTIFIED_DESC @418
COPY ~spell_rev\spwi1##\scrl75.itm~      ~override~
  SAY NAME2 @417    SAY IDENTIFIED_DESC   @418
END
```
Thanks.

**Comment by lambda-dom** [comment]
I am not going to litter the code with ad-hoc compatibility for some random mod, unless it is one that it is explicitly expected to be compatible with (typical example: SCS).

Having said this, there are a couple of alternatives:

1. Bake compatibility directly into cursed items, if the author(s) are willing. I can help with that, if you tell me what exactly is the problem.
2. Cook up a compatibility shim mod. This should be pretty easy, given the code above, but any help needed just holler.

Going to leave this open for a while, so if you have anything to add to change my mind, feel free to chime; otherwise will close this.

**Comment by Salk73** [comment]
I am the (co)author of the "random mod" and how my suggested change could be seen as an "littering" is a mystery to me, honestly.

Since Spell Revisions overwrites the description of spells there is nothing that I can do other than recommend installing Spell Revisions before Cursed Items Revision.

By the way, I and original SR and IR authors Demivrgvs and Mike1072, have worked together in the past to [make sure that their modifications and mine were fully compatible](https://www.gibberlings3.net/forums/topic/26482-ir-v4-beta-last-update-20-june-2017/page/6/#comment-230571). While I have no evidence since they seem to have retired from the modding scene several years ago, I am quite sure they would have not had any kind of problem in accepting my recommendation in the interest of full compatibility.

Feel free to close this as I have no other arguments in support of what I maintain would simply be a sensible choice.
