### ISSUE TITLE
Minor string index issue on BG1EE

### ISSUE THREAD

**Issue by Doomathon** [Gibberlings3/SpellRevisions#7]
The name strings for the item forms of all Familiars are pointing to the incorrect strings in the dialog.tlk. When I installed the v4 beta release, cast Find Familiar, and put it into the my backpack, I expected the string for the item name to read "Familiar", like it does in the unmodded game.

Instead it was some other string where Tiax is unamused by my insults, or something or other.

I didn't notice any functional issues, and I was able to fix it on my local install with NearInfinity, but figured it should be reported as an issue, however minor an issue it is.

**Comment by DEMIURGO83** [comment]
Yeah, I’ll have to give a different string ref depending on install type (old or EE) because EE developers had the wonderful idea of changing a lot of string references. :/


P.S I don’t remember you as a beta tester, did you just staryed using it with the recent open beta? 😊 If yes, welcome on board. 😉





Da: Alex Teixeira
Data invio: ‎lunedì‎ ‎4‎ ‎gennaio‎ ‎2016 ‎19‎:‎33
A: Gibberlings3/SpellRevisions





The name strings for the item forms of all Familiars are pointing to the incorrect strings in the dialogtlk When I installed the v4 beta release, cast Find Familiar, and put it into the my backpack, I expected the string for the item name to read "Familiar", like it does in the unmodded game

Instead it was some other string where Tiax is unamused by my insults, or something or other

I didn't notice any functional issues, and I was able to fix it on my local install with NearInfinity, but figured it should be reported as an issue, however minor an issue it is

**Comment by Doomathon** [comment]
To the question about Beta Testing: Yeah, took advantage of the recent open betas for both SR and IR, and have been greatly enjoying both. This was (in a few days of playing) the only unreported issue I'd found.

Keep up the good work, both in terms of well designed/fun content and a reasonably bug free experience :)

**Comment by DEMIURGO83** [comment]
I fixed the issue by assigning "new names" on install to those .cre files. This way it should work fine on both old and EE games.
