### ISSUE TITLE
Sleep appears to be broken

### ISSUE THREAD

**Issue by ChitownWillie** [Gibberlings3/SpellRevisions#94]
Installed :

SPELL_REV/SETUP-SPELL_REV.TP2~ #0 #0 // Spell Revisions: v4 Beta 19 Alpha

Combat log verifies "Unconscious":

![image](https://user-images.githubusercontent.com/65503897/165773095-9f61a42c-2e92-4b9a-9cef-6b63274379c0.png)

Visually, creature displays "sleep" effects:

![image](https://user-images.githubusercontent.com/65503897/165773302-61fabf14-a167-4607-b30e-be648675ce2c.png)

But then creature does not remain asleep and just immediately gets up.

Mods affecting SPWI116.SPL:
00000: /* created or unbiffed */ SPELL_REV/SETUP-SPELL_REV.TP2~ 0 0 // Spell Revisionsv4 Beta 19 Alpha
00001:  STRATAGEMS/SETUP-STRATAGEMS.TP2~ 0 5900 // Initialise AI components (required for all tactical and AI components)34.3

**Comment by lambda-dom** [comment]
I have just looked up the implementation if sleep and is a bit convoluted because it is designed to guarantee that if a sleeping creature is hit then it wakes up (this is much easier to set up in the EEs). So my question to you is: is the creature being hit between sleeping and awaking or taking any sort of damage -- things like poison clouds and poison damage apply.

**Comment by ChitownWillie** [comment]
Hello,

No, hits are not the issue.

In fact, the same thing happened when Zordral at the Nashkel Carnival cast
Sleep on my party.

**Comment by lambda-dom** [comment]
Hmmm, I am out of ideas. I have not seen this issue, or something close to it, reported anywhere else, and it *could* be an Engine bug. Keeping it open; will compare with SRR implementation to see if there is anything I am missing.

**Comment by ChitownWillie** [comment]
Here's a quick video:

https://youtu.be/BWzGX2WYSqA

Reinstalled with:

~SPELL_REV/SETUP-SPELL_REV.TP2~ #0 #0 // Spell Revisions: v4.19beta

**Comment by ChitownWillie** [comment]
And only 2 mods affecting Sleep:

Mods affecting SPWI116.SPL:
00000: /* created or unbiffed */ ~SPELL_REV/SETUP-SPELL_REV.TP2~ 0 0 //
Spell Revisionsv4.19beta
00001:  ~STRATAGEMS/SETUP-STRATAGEMS.TP2~ 0 5900 // Initialise AI
components (required for all tactical and AI components)34.3

**Comment by ChitownWillie** [comment]
Don't think I had the problem when I went with SR + SRR:

~SPELL_REV/SETUP-SPELL_REV.TP2~ #0 #0 // Spell Revisions: v4 Beta 18
(Revised v1.3.800)

Did something change w/ v19? Or perhaps SRR corrected it?

**Comment by subtledoctor** [comment]
I just tested and I see something similar:
- create a scroll of Sleep
- cast it at a gnoll
- the gnoll falls over
- about one second later the gnoll wakes up
- the bit where they are Slowed for a second upon getting up is functioning

My guess is, either 1) the way SR codes it to enable that Slow effect is indadvertently triggering it immediately, or 2) some mod like SCS or SoB is applying harmless background spells to the creatures, and the wake-on-hit option in EE opcode 39 is too sensitive and triggering when any spell effect is applied, regardless of damage or hostility. (I see this kind of sensitivity in SR Nishruu, for example, which constantly heal in my game because of some minor background spells.)

I can look at my files tomorrow to get a sense of how to fix.

**Comment by ChitownWillie** [comment]
Ok, thanks.

**Comment by lambda-dom** [comment]
Have just looked at the SRR implementation and it is basically the same as SR. SCS does some surgery on the spell, but I do not understand what it is trying to do so cannot say if it has any influence, but if you are willing to test it out could you please report the results? To test it, just go into the SR folder and copy spwi1##/spwi116*.* into override (using unix globbing that should also work on windows -- it should copy three files, 2 spl and one eff). These are the unpatched versions (I don't think SR does any post-copy patching to sleep but honestly, would have to double check).

**Comment by lambda-dom** [comment]
With the new patch by subtledoctor, closing this issue. If it resurfaces, we can reopen or file a new one.

**Comment by lambda-dom** [comment]
I cannot read: subtledoctor dropped the patch, not commit it. Re-opening the issue, if nothing else, as a reminder that there is a (potential) problem here.

**Comment by GraionDilach** [comment]
Note that https://github.com/Gibberlings3/SpellRevisions/pull/98/commits/9f67e4ec1d00b84bf4b6fde4c71ceb33483571f0 was merged with including the sleep change proposal, so this got in (seems doc reused the same branch for two PRs).

**Comment by lambda-dom** [comment]
New patch submitted and applied, so closing the issue. If the problem persists, re-open it.
